import Platform from './components/Platform';
import Map from './components/HMap';
import Circle from './components/HMap/objects/Circle';
import Marker from './components/HMap/objects/Marker';
import Polygon from './components/HMap/objects/Polygon';
import PolyLine from './components/HMap/objects/PolyLine';
import Rectangle from './components/HMap/objects/Rectangle';
import Route from './components/Route';
import Layer from './components/Layer';
import GeoCode from './components/GeoCode';
import Places from './components/Places';

export const HPlatform = Platform;
export const HMap = Map;
export const HMapCircle = Circle;
export const HMapMarker = Marker;
export const HMapPolygon = Polygon;
export const HMapPolyLine = PolyLine;
export const HMapRectangle = Rectangle;
export const HMapRoute = Route;
export const HMapLayer = Layer;
export const HMapGeoCode = GeoCode;
export const HMapPlaces = Places;
