import HPlatform from "./components/Platform";
import Map from "./components/HMap";
import PolyLine from "./components/HMap/objects/PolyLine";
import Polygon from "./components/HMap/objects/Polygon";
import Marker from "./components/HMap/objects/Marker";
import Circle from "./components/HMap/objects/Circle";
import Rectangle from "./components/HMap/objects/Rectangle";
import GeoCode from "./components/GeoCode";
import Route from "./components/Route";
import Layer from "./components/Layer";
import Places from "./components/Places";

export const HMapPolyLine = PolyLine;
export const HMapPolygon = Polygon;
export const HMapMarker = Marker;
export const HMapCircle = Circle;
export const HMapRectangle = Rectangle;
export const HMapRoute = Route;
export const HMapLayer = Layer;
export const HMapGeoCode = GeoCode;
export const HMapPlaces = Places;
export const HMap = Map;
export default HPlatform;
