name: CI
on: [push]
jobs:
  build-and-deploy:
    name: Build, lint, and test on Node 14.x

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # - name: Lint
      #   run: yarn lint

      # - name: Test
      #   run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build && yarn build-storybook
      
      - name: Deploy storybook 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static # The folder the action should deploy.
